### ISSUE TITLE
v4.2.1 hex package fails to compile - force_build: true but Rust source not included

### ISSUE THREAD

**Issue by dbhowmick** [kreuzberg-dev/kreuzberg#333]
The kreuzberg v4.2.1 hex package cannot be compiled because `lib/kreuzberg/native.ex` has `force_build: true` set, but the hex package
doesn't include the Rust source code needed to build from source.

**Steps to Reproduce:**

1. Add {:kreuzberg, "~> 4.2"} to mix.exs
2. Run mix deps.get && mix compile

Error:

== Compilation error in file lib/kreuzberg/native.ex ==
** (RuntimeError) Rustler dependency is needed to force the build. Add it to your `mix.exs` file: `{:rustler, ">= 0.0.0", optional:
true}`

Adding rustler as suggested, then fails with:

Unable to update /path/to/project/crates/kreuzberg
No such file or directory (os error 2)

**Root Cause:**

In deps/kreuzberg/lib/kreuzberg/native.ex:9, force_build: true is set. This forces source compilation, but
deps/kreuzberg/native/kreuzberg_rustler/Cargo.toml references:

kreuzberg = { path = "../../../../crates/kreuzberg", ... }

This path doesn't exist in the hex package since only packages/elixir is published, not the full repo with crates/.

**Workaround:**

Pin to v4.1.2 which uses precompiled binaries correctly:
{:kreuzberg, "== 4.1.2"}

**Additional Note:**

v4.2.0 also has issues - checksum mismatch when downloading precompiled binaries.

**Environment:**
- Elixir 1.19 / OTP 28
- Linux x86_64

**Comment by Goldziher** [comment]
## Root Cause Identified and Fixed

The issue was caused by an unconditional `force_build: true` setting that was accidentally introduced in commit 46065d085.

### What Happened
- **Commit intent**: "Added force_build for test/dev environments to compile NIF locally"
- **Actual implementation**: Changed to unconditional `force_build: true`
- **Result**: Production installs tried to build from source but the hex package doesn't include `crates/kreuzberg/` path dependency

### The Fix
Changed `force_build` to be conditional:
```elixir
force_build: Mix.env() in [:test, :dev],
```

This means:
- ✅ **Local development** (test/dev): Builds from source
- ✅ **Production installs**: Uses precompiled binaries from GitHub releases
- ✅ **Hex package works** without requiring full repo

### Next Steps
This fix is committed and will be included in the next release (v4.2.3+). In the meantime, you can:
- Continue using v4.1.2 (which works correctly)
- Or patch locally if needed

Thanks for the detailed bug report!

**Comment by dbhowmick** [comment]
I was not able to test this out successfully in a dev environment (`Mix.env() == :dev`). Below are the details:

## Summary
  Compilation fails with integrity check error when using kreuzberg 4.2.3 - the checksum of the precompiled NIF does not match.

  ## Environment
  - **Elixir**: 1.19
  - **Platform**: Linux 6.17.0-8-generic
  - **Kreuzberg Version**: 4.2.3 (resolved from `~> 4.2` specification)
  - **Rustler Precompiled**: 0.8.4

  ## Steps to Reproduce
  1. Add kreuzberg to mix.exs dependencies:
     ```elixir
     {:kreuzberg, "~> 4.2"}
  2. Run `mix deps.get`
  3. Run `mix compile`

  ### Expected Behavior

  The project should compile successfully with the precompiled NIF downloaded and loaded correctly.

  ### Actual Behavior

  Compilation fails with a RuntimeError during the kreuzberg dependency compilation:

  == Compilation error in file lib/kreuzberg/native.ex ==
  ** (RuntimeError) Error while downloading precompiled NIF: the integrity check failed because the checksum of files does not match.

  You can force the project to build from scratch with:

      config :rustler_precompiled, :force_build, kreuzberg: true

  In order to force the build, you also need to add Rustler as a dependency in your `mix.exs`:

      {:rustler, ">= 0.0.0", optional: true}

      lib/kreuzberg/native.ex:4: (module)
  could not compile dependency :kreuzberg, "mix compile" failed.

  ### Dependency Resolution Details

  When running mix deps.get, kreuzberg resolves to version 4.2.3 from Hex:
  - Package source: Hex package manager
  - Version constraint: ~> 4.2
  - Resolved version: 4.2.3

**Comment by dbhowmick** [comment]
This is working fine with version `4.2.4`. Hence, closing this issue.

```
☁  chunking_test  mix deps.update kreuzberg
Resolving Hex dependencies...
Resolution completed in 0.024s
Unchanged:
  castore 1.0.17
  db_connection 2.9.0
  decimal 2.3.0
  dialyxir 1.4.7
  ecto 3.13.5
  ecto_sql 3.13.4
  erlex 0.2.8
  finch 0.21.0
  hpax 1.0.3
  jason 1.4.4
  mime 2.0.7
  mint 1.7.1
  nimble_options 1.1.1
  nimble_pool 1.1.0
  pgvector 0.3.1
  postgrex 0.22.0
  req 0.5.17
  rustler_precompiled 0.8.4
  statistex 1.1.0
  telemetry 1.3.0
Upgraded:
  kreuzberg 4.2.3 => 4.2.4
* Updating kreuzberg (Hex package)
☁  chunking_test  mix compile
==> kreuzberg
Compiling 25 files (.ex)

23:09:00.555 [debug] Downloading NIF from https://github.com/kreuzberg-dev/kreuzberg/releases/download/v4.2.4/libkreuzberg_rustler-v4.2.4-nif-2.17-x86_64-unknown-linux-gnu.so.tar.gz

23:09:03.843 [debug] NIF cached at /home/dipayan/.cache/rustler_precompiled/precompiled_nifs/libkreuzberg_rustler-v4.2.4-nif-2.17-x86_64-unknown-linux-gnu.so.tar.gz and extracted to /home/dipayan/work/personal/development/chunking_test/_build/dev/lib/kreuzberg/priv/native/libkreuzberg_rustler-v4.2.4-nif-2.17-x86_64-unknown-linux-gnu.so.tar.gz
Generated kreuzberg app
==> dialyxir
Compiling 67 files (.ex)
Generated dialyxir app
==> postgrex
Compiling 69 files (.ex)
Generated postgrex app
==> ecto_sql
Compiling 25 files (.ex)
Generated ecto_sql app
==> pgvector
Compiling 11 files (.ex)
Generated pgvector app
==> nimble_pool
Compiling 2 files (.ex)
Generated nimble_pool app
==> finch
Compiling 14 files (.ex)
Generated finch app
==> req
Compiling 19 files (.ex)
Generated req app
==> chunking_test
Compiling 2 files (.ex)
     warning: unknown key .text in expression:

         chunk.text

     the given type does not have the given key:

         dynamic(%Kreuzberg.Chunk{
           content: term(),
           embedding: term(),
           metadata: term(),
           token_count: term(),
           start_position: term(),
           confidence: term()
         })

     where "chunk" was given the type:

         # type: dynamic(%Kreuzberg.Chunk{})
         # from: lib/chunking_test/ingestion/chunker.ex:137:40
         %Kreuzberg.Chunk{} = chunk

     typing violation found at:
     │
 139 │       content: chunk.text,
     │                      ~~~~
     │
     └─ lib/chunking_test/ingestion/chunker.ex:139:22: ChunkingTest.Ingestion.Chunker.format_chunk/2

Generated chunking_test app
☁  chunking_test
```
